spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.144.198.148:8848
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
    servlet:
      path: /
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  # 配置SpringSession
  session:
    store-type: redis
# 配置Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic