server:
  port: 9000
spring:
  application:
    name: gulimall-three-server       # 第三方服务.
  cloud:
    nacos:
      discovery:
        server-addr: 192.144.198.148:8848
    alicloud:
      access-key: ##############################
      secret-key: ##############################
      bucket: ##########
      oss:
        endpoint: ############
# 整合Redis
  redis:
    host: 127.0.0.1
    port: 6379
